name=ICM42688P-Voltino
version=2.0.0
author=Tomas Michal <michal@voltinolabs.cz>
maintainer=Tomas Michal <michal@voltinolabs.cz>
sentence=High-performance library for TDK ICM-42688-P IMU with user-friendly I2C/SPI wrappers, 20-bit HIRES FIFO, and Auto-Bandwidth limit.
paragraph=Professional library for TDK InvenSense ICM-42688-P IMU. Supports simplified SPI/I2C initialization, customizable pins for ESP32/RP2040, 20-bit High-Resolution FIFO parsing, dynamic ODR bandwidth protection, and a robust software calibration engine (Gradient Descent Sphere Fit for Accelerometer and Bias correction for Gyroscope).
category=Sensors
url=https://github.com/Tomasraketak/ICM42688P-library
architectures=*
includes=ICM42688P_voltino.h
depends=
license=MIT